# =========================================================
# AUTO-GENERATED PYTHON CODE
# Generated from Eclipse Sirius / Acceleo M2T Transformation
# Do not edit this file directly!
# =========================================================
MAP_DATA = {
    "routes": [
        {
            "route_id": "Transatlantic",
            "segments": [
                {
                    "source_name": "New York",
                    "source_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 40.64, "lon": -73.78},
                    "target_name": "Mid-Atlantic WP",
                    "target_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 45.0, "lon": -40.0},
                    "distance": 2800.0,
                    "wearEngine": 4760.0,
                    "wearFuselage": 5320.0,
                    "wearLandingGear": 180.0,
                    "seg_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    }
                },
                {
                    "source_name": "Mid-Atlantic WP",
                    "source_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 45.0, "lon": -40.0},
                    "target_name": "London",
                    "target_env": {
                        "salinity": 0.1,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 51.47, "lon": -0.46},
                    "distance": 2800.0,
                    "wearEngine": 4760.0,
                    "wearFuselage": 5320.0,
                    "wearLandingGear": 20.0,
                    "seg_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    }
                }
            ]
        },
        {
            "route_id": "Polar Express",
            "segments": [
                {
                    "source_name": "New York",
                    "source_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 40.64, "lon": -73.78},
                    "target_name": "Polar Ice Cap WP",
                    "target_env": {
                        "salinity": 0.2,
                        "temp": -20.0,
                        "erosion": 0.4
                    },
					"target_coords": {"lat": 80.0, "lon": -40.0},
                    "distance": 3800.0,
                    "wearEngine": 9373.333333333334,
                    "wearFuselage": 4560.0,
                    "wearLandingGear": 180.0,
                    "seg_env": {
                        "salinity": 0.2,
                        "temp": -20.0,
                        "erosion": 0.4
                    }
                },
                {
                    "source_name": "Polar Ice Cap WP",
                    "source_env": {
                        "salinity": 0.2,
                        "temp": -20.0,
                        "erosion": 0.4
                    },
					"source_coords": {"lat": 80.0, "lon": -40.0},
                    "target_name": "Tokyo",
                    "target_env": {
                        "salinity": 0.1,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 35.55, "lon": 139.79},
                    "distance": 7200.0,
                    "wearEngine": 17760.0,
                    "wearFuselage": 8640.0,
                    "wearLandingGear": 20.0,
                    "seg_env": {
                        "salinity": 0.2,
                        "temp": -20.0,
                        "erosion": 0.4
                    }
                }
            ]
        },
        {
            "route_id": "Equatorial Express",
            "segments": [
                {
                    "source_name": "Dubai",
                    "source_env": {
                        "salinity": 0.0,
                        "temp": 45.0,
                        "erosion": 0.9
                    },
					"source_coords": {"lat": 25.25, "lon": 55.36},
                    "target_name": "Singapore",
                    "target_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 1.36, "lon": 103.99},
                    "distance": 5800.0,
                    "wearEngine": 13920.0,
                    "wearFuselage": 8700.0,
                    "wearLandingGear": 100.0,
                    "seg_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    }
                }
            ]
        },
        {
            "route_id": "Desert Storm",
            "segments": [
                {
                    "source_name": "London",
                    "source_env": {
                        "salinity": 0.1,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 51.47, "lon": -0.46},
                    "target_name": "Dubai",
                    "target_env": {
                        "salinity": 0.0,
                        "temp": 45.0,
                        "erosion": 0.9
                    },
					"target_coords": {"lat": 25.25, "lon": 55.36},
                    "distance": 5500.0,
                    "wearEngine": 23650.0,
                    "wearFuselage": 5500.0,
                    "wearLandingGear": 20.0,
                    "seg_env": {
                        "salinity": 0.0,
                        "temp": 45.0,
                        "erosion": 0.9
                    }
                }
            ]
        },
        {
            "route_id": "Pacific Rim",
            "segments": [
                {
                    "source_name": "Tokyo",
                    "source_env": {
                        "salinity": 0.1,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 35.55, "lon": 139.79},
                    "target_name": "Deep Pacific WP",
                    "target_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 10.0, "lon": 170.0},
                    "distance": 4000.0,
                    "wearEngine": 6800.0,
                    "wearFuselage": 7600.0,
                    "wearLandingGear": 20.0,
                    "seg_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    }
                },
                {
                    "source_name": "Deep Pacific WP",
                    "source_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 10.0, "lon": 170.0},
                    "target_name": "Honolulu",
                    "target_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": 21.32, "lon": -157.92},
                    "distance": 3000.0,
                    "wearEngine": 7200.0,
                    "wearFuselage": 4500.0,
                    "wearLandingGear": 100.0,
                    "seg_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    }
                }
            ]
        },
        {
            "route_id": "The Coral Run",
            "segments": [
                {
                    "source_name": "Singapore",
                    "source_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    },
					"source_coords": {"lat": 1.36, "lon": 103.99},
                    "target_name": "Sydney",
                    "target_env": {
                        "salinity": 0.9,
                        "temp": 15.0,
                        "erosion": 0.1
                    },
					"target_coords": {"lat": -33.95, "lon": 151.18},
                    "distance": 6300.0,
                    "wearEngine": 15120.0,
                    "wearFuselage": 9450.0,
                    "wearLandingGear": 280.0,
                    "seg_env": {
                        "salinity": 0.5,
                        "temp": 36.0,
                        "erosion": 0.1
                    }
                }
            ]
        }
    ]
}
