#

pluginName = uk.ac.kcl.variant3.model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_FlightModel_type = Flight Model
_UI_Airport_type = Airport
_UI_EnvironmentType_type = Environment Type
_UI_FlightRoute_type = Flight Route
_UI_FlightSegment_type = Flight Segment
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_FlightModel_airports_feature = Airports
_UI_FlightModel_routes_feature = Routes
_UI_FlightModel_library_feature = Library
_UI_Airport_name_feature = Name
_UI_EnvironmentType_name_feature = Name
_UI_EnvironmentType_erosionIndex_feature = Erosion Index
_UI_EnvironmentType_salinityLevel_feature = Salinity Level
_UI_FlightRoute_id_feature = Id
_UI_FlightRoute_segments_feature = Segments
_UI_FlightSegment_distance_feature = Distance
_UI_FlightSegment_source_feature = Source
_UI_FlightSegment_target_feature = Target
_UI_FlightSegment_environment_feature = Environment
_UI_Unknown_feature = Unspecified

_UI_FlightSegment_accumulatedWear_feature = Accumulated Wear
_UI_EnvironmentType_ambientTemp_feature = Ambient Temp
_UI_Airport_code_feature = Code
_UI_Airport_environment_feature = Environment
_UI_FlightSegment_wearTotal_feature = Wear Total
_UI_FlightSegment_wearEngine_feature = Wear Engine
_UI_FlightSegment_wearFuselage_feature = Wear Fuselage
_UI_FlightSegment_wearLandingGear_feature = Wear Landing Gear
_UI_ComponentCategory_ENGINE_literal = ENGINE
_UI_ComponentCategory_FUSELAGE_literal = FUSELAGE
_UI_ComponentCategory_LANDING_GEAR_literal = LANDING_GEAR
_UI_RouteNode_type = Route Node
_UI_Waypoint_type = Waypoint
_UI_FlightModel_waypoints_feature = Waypoints
_UI_RouteNode_environment_feature = Environment
_UI_RouteNode_latitude_feature = Latitude
_UI_RouteNode_longitude_feature = Longitude
_UI_RouteNode_name_feature = Name
